apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: epgs.aci.aw
spec:
  group: aci.aw
  names:
    kind: Epg
    listKind: EpgList
    plural: epgs
    singular: epg
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI EPG"
      type: object
      properties:
        spec:
          required: ["epg_contract_masters", "provided_contracts", "consumed_contracts"]
          type: object
          properties:
            epg_contract_masters:
              type: array
              items:
                type: string
            provided_contracts:
              type: array
              items:
                type: string
            consumed_contracts:
              type: array
              items:
                type: string
