
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contracts.aci.aw
spec:
  group: aci.aw
  names:
    kind: Contract
    listKind: ContractList
    plural: contracts
    singular: contract
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: "ACI CNI Contract"
        type: object
        properties:
          spec:
            #required: ["allow_list"]
            type: object
            properties:
              allow_list:
                type: array
                items:
                  type: object
                  properties:
                    protocol:
                      type: string
                      enum:
                      - icmp
                      - tcp
                      - udp
                    ports:
                      type: object
                      properties:
                        start:
                          format: int64
                          maximum: 65535
                          minimum: 1
                          type: integer
                        end:
                          format: int64
                          maximum: 65535
                          minimum: 1
                          type: integer
            required:
            - allow_list
    served: true
    storage: true
    subresources:
      status: {}