---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-ansible-operator
  namespace: aci-containers-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aci-ansible-operator
  template:
    metadata:
      labels:
        name: aci-ansible-operator
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      serviceAccountName: aci-ansible-operator
      containers:
        - name: aci-ansible-operator
          # TBD: use official repo
          image: "noirolabs/apoorva:version_comp_test_1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - mountPath: /usr/local/etc/aci-cert/
            name: aci-user-cert-volume
          - name: aci-containers-config-volume
            mountPath: /opt/ansible/aci-containers-config/
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aci-ansible-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
        - name: aci-containers-config-volume
          configMap:
            name: aci-containers-config
        - name: aci-user-cert-volume
          secret:
            defaultMode: 420
            secretName: aci-user-cert
