---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 210}}}" .
platforms:
- name: cluster
  groups:
  - k8s
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-aci-containers-system}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy
        template_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/templates
        cluster_conf_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/cluster/config
        # TBD: use the official repo
        operator_image: ${OPERATOR_IMAGE:-"noirolabs/vishal:molecule"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
  env:
    #K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/.kube/config"}
    K8S_AUTH_KUBECONFIG: ${MOLECULE_PROJECT_DIRECTORY}/molecule/cluster/config/kubeconfig
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
