---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  vars:
    epg_custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/aci.aw_v1_epg_cr.yaml'])) | from_yaml }}"
    contract_custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/aci.aw_v1_contract_cr.yaml'])) | from_yaml }}"
    new_epg_cr:
      apiVersion: '{{ epg_custom_resource.apiVersion }}'
      kind: '{{ epg_custom_resource.kind }}'
      metadata:
        name: '{{ epg_custom_resource.metadata.name }}'
        namespace: '{{ epg_custom_resource.metadata.namespace }}'
      spec:
        epg_contract_masters:
          - aci-containers-istio
          - aci-containers-system
        provided_contracts: []
        consumed_contracts:
          - c3
          - c4
    new_contract_cr:
      apiVersion: '{{ contract_custom_resource.apiVersion }}'
      kind: '{{ contract_custom_resource.kind }}'
      metadata:
        name: '{{ contract_custom_resource.metadata.name }}'
        namespace: '{{ contract_custom_resource.metadata.namespace }}'
      spec:
        allow_list:
          - protocol: udp
            ports:
              start: 5001
              end: 5010
          - protocol: tcp
            ports:
              start: 5002
              end: 5002

    jsonVar: "{{ lookup('file', '/'.join([cluster_conf_dir, 'controller-config'])) | from_json }}"
    user: admin
    passwd: noir0123
    prefix: "{{ jsonVar['aci-prefix'] }}"
    tenant: "{{ jsonVar['aci-policy-tenant'] }}"
    ap: 'aci-containers-{{ prefix }}'
    apicHosts: "{{ jsonVar['apic-hosts'] }}"
    apicHost: "{{ apicHosts | random }}"
  tasks:
    - debug:
        msg: "EPG name: {{ new_epg_cr }}, Contract name: {{ new_contract_cr }}"

    # Test the create case
    - name: Create the aci.aw/v1.Epg and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ epg_custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"
    - name: Set the empty lists
      set_fact:
        pContractList: []
        cContractList: []
        contractMasterList: []

    # Add 2 contracts without the annotaion, which means they won't
    # be managed by the oeprator so they should always be there.
    - name: Create the extra provider contract
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: provider
        contract: extra-provider-contract
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: present
    - name: Create the extra consumer contract
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: consumer
        contract: extra-consumer-contract
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: present

    # Add a master EPG without the annotaion, which means it won't
    # be managed by the oeprator so it should always be there.
    - name: Create the extra master EPG
      cisco.aci.aci_epg_to_contract_master:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_master_ap: '{{ ap }}'
        contract_master_epg: aci-containers-nodes
        state: present
        use_proxy: no
        use_ssl: yes
        validate_certs: no

    - name: Query all the provided contracts to EPG
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: provider
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Provider contract: {{ item.fvRsProv.attributes.tnVzBrCPName }}'
      with_items: '{{ query_result.current[0].fvAEPg.children }}'
      when: query_result.current[0].fvAEPg.children is defined
    - name: Set the contract list
      set_fact:
        pContractList: "{{ pContractList + [item.fvRsProv.attributes.tnVzBrCPName] }}"
      with_items: "{{ query_result.current[0].fvAEPg.children }}"
      when: query_result.current[0].fvAEPg.children is defined
    - debug:
        msg: 'pContract list: {{ pContractList }}'
    - name: Contract assertion
      assert:
        that: pContractList | sort == (epg_custom_resource.spec.provided_contracts + ['extra-provider-contract']) | sort

    - name: Query all the consumed contracts to EPG
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: consumer
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Consumer contract: {{ item.fvRsCons.attributes.tnVzBrCPName }}'
      with_items: '{{ query_result.current[0].fvAEPg.children }}'
      when: query_result.current[0].fvAEPg.children is defined
    - name: Set the contract list
      set_fact:
        cContractList: "{{ cContractList + [item.fvRsCons.attributes.tnVzBrCPName] }}"
      with_items: "{{ query_result.current[0].fvAEPg.children }}"
      when: query_result.current[0].fvAEPg.children is defined
    - debug:
        msg: 'cContract list: {{ cContractList }}'
    - name: Contract assertion
      assert:
        that: cContractList | sort == (epg_custom_resource.spec.consumed_contracts + ['extra-consumer-contract']) | sort

    - name: Query Master EPGs
      aci_rest:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        method: get
        use_ssl: yes
        validate_certs: no
        path: /api/node/class/fvRsSecInherited.json
      register: query_result
    - debug:
        msg: 'master EPG: {{ item.fvRsSecInherited.attributes.tDn.split("/")[-1][4:] }}'
      with_items: '{{ query_result.imdata }}'
      when: query_result.imdata is defined
    - name: Set the master EPGs list
      vars:
        epgPath: 'uni/tn-{{ tenant }}/ap-{{ ap }}/epg-{{ epg_custom_resource.metadata.name }}'
      set_fact:
        contractMasterList: "{{ contractMasterList + [item.fvRsSecInherited.attributes.tDn.split('/')[-1][4:]] }}"
      with_items: "{{ query_result.imdata }}"
      when: (query_result.imdata is defined) and (epgPath in item.fvRsSecInherited.attributes.dn)
    - debug:
        msg: 'master EPG list: {{ contractMasterList }}'
    - name: master EPGs assertion
      assert:
        that: contractMasterList | sort == (epg_custom_resource.spec.epg_contract_masters + ['aci-containers-nodes']) | sort

    # Test the udpate case
    - name: Update the aci.aw/v1.Epg and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ new_epg_cr }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Running
          status: "True"
    # Wait for the update to be deployed to APIC
    - pause: seconds=90
    - name: Reset the empty lists
      set_fact:
        pContractList: []
        cContractList: []
        contractMasterList: []

    - name: Query all the provided contracts to EPG
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: provider
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Provider contract: {{ item.fvRsProv.attributes.tnVzBrCPName }}'
      with_items: '{{ query_result.current[0].fvAEPg.children }}'
      when: query_result.current[0].fvAEPg.children is defined
    - name: Set the contract list
      set_fact:
        pContractList: "{{ pContractList + [item.fvRsProv.attributes.tnVzBrCPName] }}"
      with_items: "{{ query_result.current[0].fvAEPg.children }}"
      when: query_result.current[0].fvAEPg.children is defined
    - debug:
        msg: 'pContract list: {{ pContractList }}'
    - name: Contract assertion
      assert:
        that: pContractList | sort == (new_epg_cr.spec.provided_contracts + ['extra-provider-contract']) | sort

    - name: Query all the consumed contracts to EPG
      aci_epg_to_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        contract_type: consumer
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Consumer contract: {{ item.fvRsCons.attributes.tnVzBrCPName }}'
      with_items: '{{ query_result.current[0].fvAEPg.children }}'
      when: query_result.current[0].fvAEPg.children is defined
    - name: Set the contract list
      set_fact:
        cContractList: "{{ cContractList + [item.fvRsCons.attributes.tnVzBrCPName] }}"
      with_items: "{{ query_result.current[0].fvAEPg.children }}"
      when: query_result.current[0].fvAEPg.children is defined
    - debug:
        msg: 'cContract list: {{ cContractList }}'
    - name: Contract assertion
      assert:
        that: cContractList | sort == (new_epg_cr.spec.consumed_contracts + ['extra-consumer-contract']) | sort

    - name: Query Master EPGs
      aci_rest:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        method: get
        use_ssl: yes
        validate_certs: no
        path: /api/node/class/fvRsSecInherited.json
      register: query_result
    - debug:
        msg: 'master EPG: {{ item.fvRsSecInherited.attributes.tDn.split("/")[-1][4:] }}'
      with_items: '{{ query_result.imdata }}'
      when: query_result.imdata is defined
    - name: Set the master EPGs list
      vars:
        epgPath: 'uni/tn-{{ tenant }}/ap-{{ ap }}/epg-{{ epg_custom_resource.metadata.name }}'
      set_fact:
        contractMasterList: "{{ contractMasterList + [item.fvRsSecInherited.attributes.tDn.split('/')[-1][4:]] }}"
      with_items: "{{ query_result.imdata }}"
      when: (query_result.imdata is defined) and (epgPath in item.fvRsSecInherited.attributes.dn)
    - debug:
        msg: 'master EPG list: {{ contractMasterList }}'
    - name: master EPGs assertion
      assert:
        that: contractMasterList | sort == (new_epg_cr.spec.epg_contract_masters + ['aci-containers-nodes']) | sort

    # Test the delete case
    - name: Delete the aci.aw/v1.Epg
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: '{{ epg_custom_resource }}'
        wait: yes
    - name: query the non-existent EPG
      aci_epg:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        ap: '{{ ap }}'
        epg: '{{ epg_custom_resource.metadata.name }}'
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: query
      register: query_result
    - name: EPG assertion
      assert:
        that: query_result.current == []

    # Test the create case
    - name: Create the aci.aw/v1.Contract and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ contract_custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"

    - name: query the contract
      aci_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        contract: '{{ contract_custom_resource.metadata.name }}'
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: query
      register: query_result
    - name: Contract assertion
      assert:
        that: query_result.current != []

    # Add an entry without the annotaion, which means it won't
    # be managed by the oeprator so it should always be there.
    - name: Create the extra entry
      aci_filter_entry:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        filter: '{{ contract_custom_resource.metadata.name }}-default'
        entry: test-entry
        ether_type: 'ip'
        ip_protocol: icmp
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: present

    - name: Query contract entries
      aci_filter_entry:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        filter: '{{ contract_custom_resource.metadata.name }}-default'
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Entry: {{ item.vzEntry.attributes.name }}'
      with_items: "{{ query_result.current[0].vzFilter.children }}"
      when: query_result.current[0].vzFilter.children is defined
    - name: Set the default entry list
      set_fact:
        entryList: []
    - name: Set the entry list
      set_fact:
        entryList: "{{ entryList + [item.vzEntry.attributes.name] }}"
      with_items: "{{ query_result.current[0].vzFilter.children }}"
      when: query_result.current[0].vzFilter.children is defined
    - debug:
        msg: 'entry list: {{ entryList }}'
    - name: Set the default CRD entry list
      set_fact:
        crdEntryList: ['test-entry']
    - name: Set the tcp/udp CRD entry list
      set_fact:
        crdEntryList: "{{ crdEntryList + ['-'.join((item.protocol, item.ports.start|string(), item.ports.end|string()))] }}"
      with_items: "{{ contract_custom_resource.spec.allow_list }}"
      when: (contract_custom_resource.spec.allow_list is defined) and (item.ports is defined)
    - name: Set the icmp CRD entry list
      set_fact:
        crdEntryList: "{{ crdEntryList + ['-'.join((item.protocol, 'unspecified', 'unspecified'))] }}"
      with_items: "{{ contract_custom_resource.spec.allow_list }}"
      when: (contract_custom_resource.spec.allow_list is defined) and (item.ports is not defined)
    - debug:
        msg: 'CRD entry list: {{ crdEntryList }}'
    - name: Entry list assertion
      assert:
        that: crdEntryList | sort == entryList | sort

    # Test the udpate case
    - name: Update the aci.aw/v1.Contract and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ new_contract_cr }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Running
          status: "True"
    # Wait for the update to be deployed to APIC
    - pause: seconds=60

    - name: query the contract
      aci_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        contract: '{{ contract_custom_resource.metadata.name }}'
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: query
      register: query_result
    - name: Contract assertion
      assert:
        that: query_result.current != []

    - name: Query contract entries
      aci_filter_entry:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        filter: '{{ contract_custom_resource.metadata.name }}-default'
        state: query
        output_level: info
        use_proxy: no
        use_ssl: yes
        validate_certs: no
      register: query_result
    - debug:
        msg: 'Entry: {{ item.vzEntry.attributes.name }}'
      with_items: "{{ query_result.current[0].vzFilter.children }}"
      when: query_result.current[0].vzFilter.children is defined
    - name: Set the default entry list
      set_fact:
        entryList: []
    - name: Set the entry list
      set_fact:
        entryList: "{{ entryList + [item.vzEntry.attributes.name] }}"
      with_items: "{{ query_result.current[0].vzFilter.children }}"
      when: query_result.current[0].vzFilter.children is defined
    - debug:
        msg: 'entry list: {{ entryList }}'
    - name: Set the default CRD entry list
      set_fact:
        crdEntryList: ['test-entry']
    - name: Set the tcp/udp CRD entry list
      set_fact:
        crdEntryList: "{{ crdEntryList + ['-'.join((item.protocol, item.ports.start|string(), item.ports.end|string()))] }}"
      with_items: "{{ new_contract_cr.spec.allow_list }}"
      when: (new_contract_cr.spec.allow_list is defined) and (item.ports is defined)
    - name: Set the icmp CRD entry list
      set_fact:
        crdEntryList: "{{ crdEntryList + ['-'.join((item.protocol, 'unspecified', 'unspecified'))] }}"
      with_items: "{{ new_contract_cr.spec.allow_list }}"
      when: (new_contract_cr.spec.allow_list is defined) and (item.ports is not defined)
    - debug:
        msg: 'CRD entry list: {{ crdEntryList }}'
    - name: Entry list assertion
      assert:
        that: crdEntryList | sort == entryList | sort

    # Test the delete case
    - name: Delete the aci.aw/v1.Contract
      k8s:
        state: absent
        namespace: '{{ namespace }}'
        definition: '{{ contract_custom_resource }}'
        wait: yes
    - name: query the non-existent contract
      aci_contract:
        host: '{{ apicHost }}'
        username: '{{ user }}'
        password: '{{ passwd }}'
        tenant: '{{ tenant }}'
        contract: '{{ contract_custom_resource.metadata.name }}'
        use_ssl: yes
        validate_certs: no
        use_proxy: no
        state: query
      register: query_result
    - name: Contract assertion
      assert:
        that: query_result.current == []

    - name: Get Pods
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Example assertion
      assert:
        that: (pods | length) > 0
