---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  vars:
    epg_custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/aci.aw_v1_epg_cr.yaml'])) | from_yaml }}"
    contract_custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/aci.aw_v1_contract_cr.yaml'])) | from_yaml }}"

  tasks:
    - name: Create the aci.aw/v1.Epg and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ epg_custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"

    - name: Create the aci.aw/v1.Contract and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ contract_custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"

    - name: Get Pods
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Example assertion
      assert:
        that: (pods | length) > 0
