---
- name: ACI ansible operator EPG Playbook
  connection: local
  hosts: localhost
  vars:
    jsonVar: "{{ lookup('file', '/opt/ansible/aci-containers-config/controller-config') | from_json }}"
    prefix: "{{ jsonVar['aci-prefix'] }}"
    user: "{{ jsonVar['apic-username'] }}"
    tenant: "{{ jsonVar['aci-policy-tenant'] }}"
    certKey: "{{ jsonVar['apic-private-key-path'] }}"
    vmProvider: "{{ jsonVar['aci-vmm-type'] | lower }}"
    vmmDomain: "{{ jsonVar['aci-vmm-domain'] }}"
    ap: 'aci-containers-{{ prefix }}'
    bd: 'aci-containers-{{ prefix }}-pod-bd'
    apicHosts: "{{ jsonVar['apic-hosts'] }}"
    apicHost: "{{ apicHosts | random }}"
    epgName: '{{ meta.name }}'
    masterEpgs: '{{ epg_contract_masters }}'
    providedContracts: '{{ provided_contracts }}'
    consumedContracts: '{{ consumed_contracts }}'
    desiredState: '{{ state }}'
  tasks:
  - name: create EPG
    aci_epg:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      bd: '{{ bd }}'
      # TBD: annotation?
      use_ssl: yes
      validate_certs: no
      use_proxy: no
      state: '{{ desiredState }}'
  - name: Query all the provided contracts to EPG
    when: desiredState == 'present'
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      username: '{{ user }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract_type: provider
      state: query
      output_level: info
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    register: query_result
  - debug:
      msg: 'Provider contract name {{ item.fvRsProv.attributes.tnVzBrCPName }}'
    with_items: '{{ query_result.current[0].fvAEPg.children }}'
    when: query_result.current[0].fvAEPg.children is defined
  - name: Delete the extra provided contracts to EPG
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract_type: provider
      contract: '{{ item.fvRsProv.attributes.tnVzBrCPName }}'
      state: absent
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    with_items: '{{ query_result.current[0].fvAEPg.children }}'
    when: (desiredState == 'present') and (query_result.current[0].fvAEPg.children is defined) and (item.fvRsProv.attributes.tnVzBrCPName not in providedContracts)
  - name: Add provided contracts to EPG
    when: desiredState == 'present'
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract: '{{ item }}'
      contract_type: provider
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: '{{ providedContracts }}'
  - name: Query all the consumed contracts to EPG
    when: desiredState == 'present'
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      username: '{{ user }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract_type: consumer
      state: query
      output_level: info
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    register: query_result
  - debug:
      msg: 'Consumer contract name {{ item.fvRsCons.attributes.tnVzBrCPName }}'
    with_items: '{{ query_result.current[0].fvAEPg.children }}'
    when: query_result.current[0].fvAEPg.children is defined
  - name: Delete the extra consumed contracts to EPG
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract: '{{ item.fvRsCons.attributes.tnVzBrCPName }}'
      contract_type: consumer
      state: absent
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    with_items: '{{ query_result.current[0].fvAEPg.children }}'
    when: (desiredState == 'present') and (query_result.current[0].fvAEPg.children is defined) and (item.fvRsCons.attributes.tnVzBrCPName not in consumedContracts)
  - name: Add consumed contracts to EPG
    when: desiredState == 'present'
    ignore_errors: yes
    aci_epg_to_contract:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract: '{{ item }}'
      contract_type: consumer
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: '{{ consumedContracts }}'
  - name: Query Master EPGs
    when: desiredState == 'present'
    ignore_errors: yes
    aci_rest:
      host: '{{ apicHost }}'
      username: '{{ user }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      method: get
      use_ssl: yes
      validate_certs: no
      path: /api/node/class/fvRsSecInherited.json
    register: query_result
  - debug:
      msg: '{{ item.fvRsSecInherited.attributes.tDn.split("/")[-1][4:] }}'
    with_items: '{{ query_result.imdata }}'
    when: query_result.imdata is defined
  - name: Delete extra Master EPGs
    vars:
      epgPath: 'uni/tn-{{ tenant }}/ap-{{ ap }}/epg-{{ epgName }}'
    cisco.aci.aci_epg_to_contract_master:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract_master_ap: '{{ ap }}'
      contract_master_epg: '{{ item.fvRsSecInherited.attributes.tDn.split("/")[-1][4:] }}'
      state: absent
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    with_items: '{{ query_result.imdata }}'
    when: (desiredState == 'present') and (query_result.imdata is defined) and (epgPath in item.fvRsSecInherited.attributes.dn) and (item.fvRsSecInherited.attributes.tDn.split("/")[-1][4:] not in masterEpgs)
  - name: Attach Master EPGs
    when: (desiredState == 'present')
    cisco.aci.aci_epg_to_contract_master:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      contract_master_ap: '{{ ap }}'
      contract_master_epg: '{{ item }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
    loop: '{{ masterEpgs }}'
  - name: Bind EPG to VMM Domain
    when: desiredState == 'present'
    aci_epg_to_domain:
      host: '{{ apicHost }}'
      cert_key: '{{ certKey }}'
      certificate_name: '{{ tenant }}.crt'
      username: '{{ user }}'
      vm_provider: '{{ vmProvider }}'
      domain: '{{ vmmDomain }}'
      domain_type: vmm
      tenant: '{{ tenant }}'
      ap: '{{ ap }}'
      epg: '{{ epgName }}'
      state: present
      use_proxy: no
      use_ssl: yes
      validate_certs: no
